# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0002_auto_20170830_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default='dato', max_length=10),
            preserve_default=False,
        ),
    ]
