# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0003_auto_20170904_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
